<!DOCTYPE html>
<html lang = "pt-BR">
<head>
	<title>Projeto - TCC</title>
	<link rel="shortcut icon" href="../img/logo.jpg" >
	<meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="../css/w3.css">
	<link rel="stylesheet" type="text/css" href="../css/bootstrap.min.css" />
	<link rel="stylesheet" type="text/css" href="../css/estilo.css" />
	<link rel="stylesheet" type="text/css" href="../css/escalacao.css" />
	<link rel="stylesheet" type="text/css" href="../css/cabecalho.css" />
	<link href = "https://fonts.googleapis.com/icon?family=Material+Icons" rel = "stylesheet"/>
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway">

	<script>
		//Função para gerar o formulário de filtro da escalação
		function geraFormFiltro(){
      var HTML = '<form id="filtrar_escalacao">'
          +'<table class="filtro">'
            +'<thead>'
              +'<tr>'
                +'<div class="row">'
                  +'<div class="col-sm-12">'
                    +'<div class="form-group">'
                      +'<td>'
                        +'<label for="saldo">Saldo disponível</label>'
                      +'</td>'
                      +'<td>'
                        +'<label for="esquemaTatico">Esquema tático</label>'
                      +'</td>'
                    +'</div>'
                  +'</div>'
                +'</div>'
              +'</tr>'
            +'</thead>'
            +'<tbody>'
              +'<tr>'
                +'<div class="row">'
                  +'<div class="col-sm-12">'
                    +'<div class="form-group">'
                      +'<td>'
                        +'<input type="number" class="form-control" name="saldo" id="saldo"/>'
                      +'</td>'
                      +'<td>'
                        +'<select name="esquemaTatico" class="form-control">'
                          +'<option value="">Selecione um esquema</option>'
                          +'<option value="3-4-3">3-4-3</option>'
                          +'<option value="3-5-2">3-5-2</option>'
                          +'<option value="4-3-3">4-3-3</option>'
                          +'<option value="4-4-2">4-4-2</option>'
                          +'<option value="4-5-1">4-5-1</option>'
                          +'<option value="5-3-2">5-3-2</option>'
                          +'<option value="5-4-1">5-4-1</option>'
                        +'</select>'
                      +'</td>'
                    +'</div>'
                  +'</div>'
                +'</div>'
              +'</tr>'
              +'<tr>'
                +'<td colspan="2">'
                  +'<button type="button" class="btn btn-custom" onclick="gerarEscalacaoFiltrada()"><b>Gerar escalação</b></button'
                +'</td>'
              +'</tr>'
            +'</tbody>'
          +'</table>'
        +'</form>';
        document.getElementById('form_filtro').innerHTML = HTML;
        gerarEscalacao();
    }

    //Função para gerar a escalação
    function gerarEscalacao(){
        var HTML = '<table class="table table-hover escalacao">'
            +'<div class="form-group">'
              +'<thead>'
                +'<tr>'
                  +'<div class="row">'
                    +'<th>'
                      +'Posição'
                    +'</th>'
                    +'<th>'
                      +'Jogador'
                    +'</th>'
                    +'<th>'
                      +'Cartoletas'
                    +'</th>'
                  +'</div>'
                +'</tr>'
              +'</thead>'
              +'<tbody>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'-'
                    +'</td>'
                    +'<td>'
                      +'C$0.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
              +'</tbody>'
            +'</div>'
          +'</table>';
          document.getElementById('escalacao').innerHTML = HTML;
    }

    //Escalação filtrada teste
    function gerarEscalacaoFiltrada(){
        var HTML = '<table class="table table-hover escalacao">'
            +'<div class="form-group">'
              +'<thead>'
                +'<tr>'
                  +'<div class="row">'
                    +'<th>'
                      +'Posição'
                    +'</th>'
                    +'<th>'
                      +'Jogador'
                    +'</th>'
                    +'<th>'
                      +'Cartoletas'
                    +'</th>'
                  +'</div>'
                +'</tr>'
              +'</thead>'
              +'<tbody>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'GOL'
                    +'</td>'
                    +'<td>'
                      +'A'
                    +'</td>'
                    +'<td>'
                      +'C$23.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'LAT'
                    +'</td>'
                    +'<td>'
                      +'B'
                    +'</td>'
                    +'<td>'
                      +'C$15.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'LAT'
                    +'</td>'
                    +'<td>'
                      +'C'
                    +'</td>'
                    +'<td>'
                      +'C$8.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'ZAG'
                    +'</td>'
                    +'<td>'
                      +'D'
                    +'</td>'
                    +'<td>'
                      +'C$15.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'ZAG'
                    +'</td>'
                    +'<td>'
                      +'E'
                    +'</td>'
                    +'<td>'
                      +'C$11.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'MEI'
                    +'</td>'
                    +'<td>'
                      +'F'
                    +'</td>'
                    +'<td>'
                      +'C$6.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'MEI'
                    +'</td>'
                    +'<td>'
                      +'G'
                    +'</td>'
                    +'<td>'
                      +'C$4.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'MEI'
                    +'</td>'
                    +'<td>'
                      +'H'
                    +'</td>'
                    +'<td>'
                      +'C$5.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'ATA'
                    +'</td>'
                    +'<td>'
                      +'I'
                    +'</td>'
                    +'<td>'
                      +'C$3.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'ATA'
                    +'</td>'
                    +'<td>'
                      +'J'
                    +'</td>'
                    +'<td>'
                      +'C$7.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'ATA'
                    +'</td>'
                    +'<td>'
                      +'K'
                    +'</td>'
                    +'<td>'
                      +'C$3.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
                +'<tr>'
                  +'<div class="row">'
                    +'<td>'
                      +'TEC'
                    +'</td>'
                    +'<td>'
                      +'L'
                    +'</td>'
                    +'<td>'
                      +'C$2.00'
                    +'</td>'
                  +'</div>'
                +'</tr>'
              +'</tbody>'
            +'</div>'
          +'</table>';
          document.getElementById('escalacao').innerHTML = HTML;
    }
    </script>
</head>
<body onload = "geraFormFiltro()">

  <!--cabeçalho-->
  <nav class="navbar navbar-expand-md cabecalho">
    <a class="navbar-brand ranking" href="#">Ranking</a>
    <a class="navbar-brand" href="home.php"><img src="../img/logo.jpg" class="cartola"/></a>
    <a class="navbar-brand escalacao" href="escalacao.php">Escalação</a>
  </nav>

  <main>
			<h1 class="text-center"><b>ESCALAÇÃO AUTOMÁTICA</b></h1>

      <div id="form_filtro" class="container">
        <!--Formulário de filtro-->
      </div>

      <div id="escalacao" class="container">
        <!--Escalação-->
      </div>
  </main>
</body>
</html>
